# Pivot Data

Many colums in the data contain lists.  To make these columns more useful, we'll split them into columns, pivot them to rows, and aggregate all of them back into on table to export to a csv.

In [1]:
import pandas as pd

In [2]:
movies = pd.read_csv('Walt_Disney_Movie_Details.csv')
movies.head()

,Title,Year,Rated,Released,Runtime,Genre,Director,Writer,Actors,Plot,...,imdbRating,imdbVotes,imdbID,Type,DVD,BoxOffice,Production,Internet Movie Database Rating,Rotten Tomatoes Rating,Metacritic Rating
0,Academy Award Review of Walt Disney Cartoons,1937,Approved,19 May 1937,41 min,"Animation, Short, Comedy, Family",NaN,NaN,"Billy Bletcher, Dorothy Compton, Eddie Holden,...",A compilation of five Oscar-winning Disney sho...,...,7.1,76,tt0263027,movie,NaN,NaN,NaN,7.1/10,NaN,NaN
1,Snow White and the Seven Dwarfs,1937,Approved,04 Feb 1938,83 min,"Animation, Family, Fantasy, Musical, Romance","William Cottrell, David Hand, Wilfred Jackson,...","Jacob Grimm (fairy tales), Wilhelm Grimm (fair...","Roy Atwell, Stuart Buchanan, Adriana Caselotti...",Exiled into the dangerous forest by her wicked...,...,7.6,"181,331",tt0029583,movie,27 Mar 2007,"$184,925,486",NaN,7.6/10,NaN,95/100
2,Pinocchio,1940,G,23 Feb 1940,88 min,"Animation, Comedy, Family, Fantasy, Musical","Norman Ferguson, T. Hee, Wilfred Jackson, Jack...","Carlo Collodi (from the story by), Ted Sears (...","Mel Blanc, Billy Bletcher, Don Brodie, Stuart ...","A living puppet, with the help of a cricket as...",...,7.4,"131,352",tt0032910,movie,27 Mar 2007,"$84,254,167",Walt Disney Productions,7.4/10,73%,99/100
3,Fantasia,1940,G,19 Sep 1941,125 min,"Animation, Family, Fantasy, Music, Musical","James Algar, Samuel Armstrong, Ford Beebe Jr.,...","Joe Grant (story direction), Dick Huemer (stor...","Deems Taylor, Leopold Stokowski, The Philadelp...",A collection of animated interpretations of gr...,...,7.7,"88,600",tt0032455,movie,27 Mar 2007,"$76,408,097",Walt Disney Productions,7.7/10,95%,96/100
4,The Reluctant Dragon,1941,Approved,20 Jun 1941,74 min,"Animation, Comedy, Family","Alfred L. Werker, Hamilton Luske, Jack Cutting...","Kenneth Grahame (based on the story by), Ted S...","Robert Benchley, Frances Gifford, Buddy Pepper...",Humorist Robert Benchley learns about the anim...,...,6.9,"2,810",tt0034091,movie,27 Mar 2007,"$872,000",Walt Disney Productions,6.9/10,68%,NaN

In [3]:
movies.columns

Index(['Title', 'Year', 'Rated', 'Released', 'Runtime', 'Genre', 'Director',
       'Writer', 'Actors', 'Plot', 'Language', 'Country', 'Awards', 'Poster',
       'Metascore', 'imdbRating', 'imdbVotes', 'imdbID', 'Type', 'DVD',
       'BoxOffice', 'Production', 'Internet Movie Database Rating',
       'Rotten Tomatoes Rating', 'Metacritic Rating'],
      dtype='object')

In [4]:
genre = movies[['imdbID', 'Genre']]
director = movies[['imdbID', 'Director']]
writer = movies[['imdbID', 'Writer']]
actors = movies[['imdbID', 'Actors']]
language = movies[['imdbID', 'Language']]
country = movies[['imdbID', 'Country']]
production = movies[['imdbID', 'Production']]

In [5]:
genre = pd.concat([genre[['imdbID']], genre['Genre'].str.split(', ', expand=True)], axis=1)
director = pd.concat([director[['imdbID']], director['Director'].str.split(', ', expand=True)], axis=1)
writer = pd.concat([writer[['imdbID']], writer['Writer'].str.split(', ', expand=True)], axis=1)
actors = pd.concat([actors[['imdbID']], actors['Actors'].str.split(', ', expand=True)], axis=1)
language = pd.concat([language[['imdbID']], language['Language'].str.split(', ', expand=True)], axis=1)
country = pd.concat([country[['imdbID']], country['Country'].str.split(', ', expand=True)], axis=1)
production = pd.concat([production[['imdbID']], production['Production'].str.split(', ', expand=True)], axis=1)

In [6]:
genre = pd.melt(genre, id_vars=['imdbID'], value_vars=[0, 1, 2, 3, 4, 5, 6])
director = pd.melt(director, id_vars=['imdbID'], value_vars=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])
writer = pd.melt(writer, id_vars=['imdbID'], value_vars=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])
actors = pd.melt(actors, id_vars=['imdbID'], value_vars=[0, 1, 2, 3])
language = pd.melt(language, id_vars=['imdbID'], value_vars=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15])
country = pd.melt(country, id_vars=['imdbID'], value_vars=[0, 1, 2, 3, 4, 5])
production = pd.melt(production, id_vars=['imdbID'], value_vars=[0, 1, 2, 3, 4, 5, 6])

In [7]:
genre['Type'] = 'Genre'
director['Type'] = 'Director'
writer['Type'] = 'Writer'
actors['Type'] = 'Actors'
language['Type'] = 'Language'
country['Type'] = 'Country'
production['Type'] = 'Production'

In [8]:
pivot = pd.concat([genre, director, writer, actors, language, country, production])
pivot.dropna(inplace=True)
pivot.drop(['variable'], axis=1, inplace=True)

In [9]:
pivot.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 12783 entries, 0 to 5373
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   imdbID  12783 non-null  object
 1   value   12783 non-null  object
 2   Type    12783 non-null  object
dtypes: object(3)
memory usage: 399.5+ KB

In [10]:
pivot.to_csv('Walt_Disney_Movie_Pivot.csv', index=False)